// Sync Engine — processes the offline queue when internet is available.
// Tries to send each queued action, removes on success, retries on failure.
//
// Idempotency & conflict resolution (per ARCHITECTURE.md §6):
//   - Each queued action carries an `idempotencyKey` (auto-generated by
//     `enqueueAction()`). The key is sent as the `Idempotency-Key` HTTP
//     header so the server can deduplicate retries safely.
//   - 409 Conflict responses are treated as "server wins": the action is
//     dequeued and counted as a conflict rather than a failure. The caller
//     can surface a UI prompt to refresh the local resource.

import { getQueuedActions, dequeueAction, incrementRetry, getQueueSize } from "./offline-queue";

export interface SyncResult {
  synced: number;
  failed: number;
  conflicts: number;
  remaining: number;
}

let syncing = false;

export async function syncQueue(): Promise<SyncResult> {
  const empty: SyncResult = { synced: 0, failed: 0, conflicts: 0, remaining: 0 };
  if (typeof window === "undefined") return empty;
  if (syncing) return { ...empty, remaining: getQueueSize() };
  if (!navigator.onLine) return { ...empty, remaining: getQueueSize() };

  syncing = true;
  let synced = 0;
  let failed = 0;
  let conflicts = 0;
  const queue = getQueuedActions();

  for (const action of queue) {
    try {
      const res = await fetch(action.url, {
        method: action.method,
        headers: {
          "Content-Type": "application/json",
          // Send the idempotency key so the server can deduplicate retries.
          // Only set if present (older queued actions may not have one).
          ...(action.idempotencyKey ? { "Idempotency-Key": action.idempotencyKey } : {}),
        },
        credentials: "include",
        body: action.body ? JSON.stringify(action.body) : undefined,
      });

      if (res.ok) {
        dequeueAction(action.id);
        synced++;
      } else if (res.status === 409) {
        // Conflict — server has a newer version (or the action was already
        // applied with a different outcome). Server wins: dequeue and
        // surface as a conflict rather than a hard failure, so the UI can
        // prompt the user to refresh their local state.
        dequeueAction(action.id);
        conflicts++;
      } else if (res.status >= 400 && res.status < 500) {
        // Client error (non-conflict) — don't retry, just remove.
        dequeueAction(action.id);
        failed++;
      } else {
        // Server error — retry
        const stillQueued = incrementRetry(action.id);
        if (!stillQueued) failed++;
      }
    } catch {
      // Network error — retry
      const stillQueued = incrementRetry(action.id);
      if (!stillQueued) failed++;
    }
  }

  syncing = false;
  return { synced, failed, conflicts, remaining: getQueueSize() };
}

// Auto-sync when coming online
export function initAutoSync(): void {
  if (typeof window === "undefined") return;
  window.addEventListener("online", () => {
    syncQueue();
  });
  // Also try syncing every 30 seconds if online
  setInterval(() => {
    if (navigator.onLine && getQueueSize() > 0) {
      syncQueue();
    }
  }, 30000);
}
